# Python Numpy Arrays

## Numpy Tutorials
    Numpy is a general purpose array-processing package. It provides a high performance multidimensional array object, and
    tools for working with these arrays. It is the fundamental package for scintific computing with Python

## What is an Array
    An array is a data structure that stores value of same data type, this is the main difference between the array
        and list in Python. While python list can contain values corresponding to different data types, arrays in python can only contain value corresponding to same data type.

In [15]:
## import the library
import numpy as np
## create a list and then change it into numpy array
lst = [1,2,3,4,5]
arr = np.array(lst)
type(arr)  # we got n dimensional numpy array


numpy.ndarray

In [4]:
## we can also check the shape of the array
np.shape(lst)

(5,)

In [5]:
## we can also create two dimensional array by providing arrays in the array
## let's create 3 list

lst1 = [1,2,3,4]
lst2 = [2,3,4,5]
lst3 = [3,4,5,6]
## use numpy library to make 2D numpy array
arr1 = np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [6]:
## we can check the shape of the array
np.shape(arr1)

(3, 4)

In [7]:
## showing (3,4) means it has 3 rows and 4 columns

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
## indexing

## we can easilt fetch the value through indexing
arr[2]

3

In [18]:
## we can also specify the range for the array
arr[:]   # print whole array

array([1, 2, 3, 4, 5])

In [19]:
arr[1:]  # print all the values after index 0

array([2, 3, 4, 5])

In [20]:
arr[1:3]

array([2, 3])

In [21]:
## we can also leave last element and print the whole array
arr[:-1]

array([1, 2, 3, 4])

In [22]:
##
arr[::]

array([1, 2, 3, 4, 5])

In [24]:
## we can also print the array in that way where we can leave one 
## element and print the next element in the array
arr[::2]

array([1, 3, 5])

In [26]:
## we can also reverse the array by adding minus(-) sign
arr[::-2]

array([5, 3, 1])

In [27]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [28]:
## we can also perform operations on the 2D array as well as
## first we have to give rows and then column
arr1[:,1]

array([2, 3, 4])

In [29]:
arr1[:2,:2]

array([[1, 2],
       [2, 3]])

In [30]:
arr1[:2,1:3]

array([[2, 3],
       [3, 4]])

In [31]:
arr1[1:,:3]

array([[2, 3, 4],
       [3, 4, 5]])

In [32]:
## EDA
## we can check some chacracteristics by performing some operations
arr

array([1, 2, 3, 4, 5])

In [33]:
## checking which items in the array is less than 3, we can also do by using for loop but that will
## be time consuming for large data set
arr<3

array([ True,  True, False, False, False])

In [35]:
## we can also get the value of item
arr[arr<3]

array([1, 2])

In [36]:
## we have 2D array
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [39]:
arr1.shape

(3, 4)

In [40]:
## we can also convert the shape of the array to (4,3)
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

In [42]:
## mechanism to create an array
np.arange(1,10,2)      #(start,end,step)

array([1, 3, 5, 7, 9])

In [43]:
## we can also reshape the array into the 2D array
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [45]:
## also perform some other operations on the array
arr

array([1, 2, 3, 4, 5])

In [46]:
arr*2

array([ 2,  4,  6,  8, 10])

In [47]:
arr*arr

array([ 1,  4,  9, 16, 25])

In [48]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [49]:
arr1*3

array([[ 3,  6,  9, 12],
       [ 6,  9, 12, 15],
       [ 9, 12, 15, 18]])

In [50]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [ 4,  9, 16, 25],
       [ 9, 16, 25, 36]])

In [52]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
## we can also get any random value between the numeber
## for e.g, we want a number between the 41 and 99 then
np.random.randint(41,99)   # we will got random integer every time when we run the code

67

In [58]:
## now if we want 4 values between specific limit
## then we can perform this\
np.random.randint(11,66,9)   # we will got 9 random values every time between 11 and 66

array([62, 60, 38, 65, 30, 34, 45, 60, 56])

In [59]:
## we can also reshape it
np.random.randint(2,33,9).reshape(3,3)

array([[18, 29,  9],
       [10, 32, 21],
       [ 5, 21, 29]])