# Pandas Library


In [1]:
##### 1. Pandas Dataframe
##### 2. Pandas Series
##### 3. Pandas Basic Operation

In [2]:
# When we used pandas to read the data from any excel file then, the data
# of that excel file is chnanged into data structure (dataframe) of
# pandas library

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
## Create DataFrame
df = pd.DataFrame(data = np.arange(0,20).reshape(5,4), index=["Row1","Row2","Row3","Row4","Row5"],
            columns=["Column1","Column2","Column3","Column4"])

In [12]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [13]:
df.tail(3)

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [16]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [17]:
## Indexing

## columnname, rowindex[loc], rowindex columnindex number[.iloc]
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [21]:
## By using Column name

df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [19]:
 df[["Column1"]]

Column1
Row1        0
Row2        4
Row3        8
Row4       12
Row5       16

In [26]:
type(df[["Column1"]])

pandas.core.frame.DataFrame

In [27]:
type(df["Column1"])

pandas.core.series.Series

In [28]:
## In series either we choosing only single row or single column
## but in dataframe we choose multiple rows and column

In [29]:
# Row Indexing

In [30]:
df.loc['Row2']

Column1    4
Column2    5
Column3    6
Column4    7
Name: Row2, dtype: int32

In [31]:
type(df.loc['Row2'])

pandas.core.series.Series

In [32]:
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [33]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [34]:
# we can also do indexing from rows and columns

In [35]:
# e.g, if we want element 8,9 ,12,13 from df, then

In [36]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [37]:
## e.g, if we want 5,6,9,10,13,14 from df

In [41]:
df.iloc[1:4,1:3]

Column2  Column3
Row2        5        6
Row3        9       10
Row4       13       14

In [44]:
df[["Column1","Column4"]]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [45]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [46]:
## convert into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [49]:
# Basic Operations

## New DataFrame
df1 = pd.DataFrame(data = [[1,np.nan,2],[1,3,4]] , index=["Row1","Row2"],
            columns=["Column1","Column2","Column3"])

In [48]:
df1

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [51]:
df1.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [52]:
df1.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [ ]:
## to check a number present how much time

In [54]:
df1["Column3"].value_counts()

2    1
4    1
Name: Column3, dtype: int64

In [55]:
## to check unique values

In [56]:
df1["Column3"].unique()

array([2, 4], dtype=int64)

In [57]:
df1["Column2"].unique()

array([nan,  3.])

In [58]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [60]:
df["Column1"].unique()

array([ 0,  4,  8, 12, 16])

In [61]:
df>3

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True